# Generated by Django 4.2.1 on 2023-06-12 14:23

from django.conf import settings
from django.db import migrations, models
import lmsAdmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email')),
                ('studentId', models.CharField(max_length=50, null=True, unique=True)),
                ('teacherId', models.CharField(max_length=50, null=True, unique=True)),
                ('image', models.ImageField(default='user/logo.jpg', upload_to=lmsAdmin.models.upload_to)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('classNo', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=12)),
                ('phone', models.CharField(default='', max_length=20)),
                ('admissionNo', models.CharField(blank=True, default='', max_length=50)),
                ('section', models.CharField(blank=True, default='', max_length=15)),
                ('in_class', models.BooleanField(default=False)),
                ('fatherName', models.CharField(blank=True, max_length=50)),
                ('fatherOccupation', models.CharField(blank=True, max_length=50)),
                ('fatherMobile', models.CharField(blank=True, max_length=20)),
                ('motherName', models.CharField(blank=True, max_length=50)),
                ('motherOccupation', models.CharField(blank=True, max_length=50)),
                ('motherMobile', models.CharField(blank=True, max_length=100)),
                ('presentAddress', models.TextField(blank=True)),
                ('permanentAddress', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=50)),
                ('experience', models.FloatField(blank=True, default=0)),
                ('education', models.TextField(blank=True)),
                ('certificate', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('is_teacher', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, related_name='classes_enrolled', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
