# Generated by Django 4.2.1 on 2023-06-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_time', models.TimeField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsAdmin.schoolclass')),
            ],
        ),
    ]
