# Generated by Django 4.2.1 on 2023-06-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsAdmin', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='clas',
            new_name='classes',
        ),
    ]
