# Generated by Django 4.2.1 on 2023-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsAdmin', '0003_rename_clas_attendance_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classes',
            field=models.CharField(max_length=30),
        ),
    ]
